<h1>Categorias</h1>

<br>

<p class="text-center">
    <a href="<?= $this->url('livraria-admin', array('controller' => 'categorias', 'action' => 'new')) ?>">Novo</a>
</p>

<table class="table table-borderless">
    <thead>
    <th>#</th>
    <th>Nome</th>
    <th>Editar</th>
    <th>Excluir</th>
</thead>
<tbody>
    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?= $entity->getId(); ?></td>
            <td><?= $entity->getNome(); ?></td>
            <td><a href="<?= $this->url('livraria-admin-interna', array('controller' => 'categorias', 'action' => 'edit', 'id' => $entity->getId())) ?>">Editar</a></td>
            <td><a href="<?= $this->url('livraria-admin-interna', array('controller' => 'categorias', 'action' => 'delete', 'id' => $entity->getId())) ?>">Excluir</a></td>
        </tr>
    <?php endforeach; ?>
</tbody>
</table>
