<h1>Categorias</h1>
<br>
<div class="container">
    <ul>
        <?php foreach ($this->dados as $entity): ?>
            <li><?= $entity->getNome(); ?>
                <ul>
                    <?php foreach ($entity->getLivros() as $livro): ?>
                        <li><?= $livro->getNome(); ?></li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php endforeach; ?>
    </ul>
</div>