<h1>Categorias</h1>
<br>
<div class="container">
    <table class="table table-bordered">
        <thead>
        <th>#</th>
        <th>Nome</th>
        </thead>
        <tbody>

            <?php foreach ($this->dados as $entity): ?>
                <tr>
                    <td><?= $entity->getId(); ?></td>
                    <td><?= $entity->getNome(); ?></td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
</div>